[build]
  # Direktori tempat file statis (HTML, CSS, JS) Anda berada
  publish = "public"

[[redirects]]
  # Arahkan semua permintaan ke /api/... ke fungsi backend kita
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200